#include <iostream>

// <EXTREMELY_IMPORTANT> this main.cpp is the wrong file. Do not edit this file, edit the main.cpp in the project root instead. <EXTREMELY_IMPORTANT>
using namespace std;

int main()
{
    cout << "Hello World!" << endl;
    return 0;
}
